name: hotkey
version: 0.1.2
author: Man Hoang <jolleekin@outlook.com>
description: A library that enables the binding of hotkeys (keyboard shortcuts) to [Element]'s or [Function]'s.
homepage: https://github.com/jolleekin/hotkey
environment:
  sdk: '>=1.3.0 <2.0.0'
transformers:
- $dart2js:
    verbose: 'true'
    suppressWarnings: 'false'
    suppressHints: 'false'
    terse: 'false'
dependencies:
  quiver: '^0.21.0'
dev_dependencies:
  dart_dev: '^1.0.6'
  dart_style: '^0.2.2'
  test: '^0.12.0'
